source("R/overview/statistics.R")
source("R/overview/variable_types.R")
source("R/variables/variables.R")

#' Profiler Function
#'
#' This function generates a profiler report for a given dataset or file.
#' It checks the type of input data and calls the appropriate profiling function 
#' for data frames or files.
#'
#' @param data A data frame or a character string representing the file path to the data.
#' @param output_file A character string specifying the name of the output markdown file 
#'                    where the profiler report will be saved. Default is "profiler_report.md".
#' @param sep A character string specifying the separator used if data is a file path, default is ",".
#'
#' @return A markdown report generated by the appropriate profiling function, either for data frames or files.
#'
#' @examples
#' # Example with a data frame
#' df <- data.frame(a = 1:5, b = letters[1:5])
#' profiler(df)
#'
#' # Example with a file path
#' profiler("data/my_data.csv")
#'
#' @export
profiler <- function(data, output_file = "profiler_report.md", sep = ",") {
    if(is.data.frame(data)) {
        return(profiler_dataframe(data, output_file))
    } else if(is.character(data)) {
        return(profiler_file(data, output_file, sep))
    } else {
        stop("Invalid input type")
    }
}

#' Read Data from File and Generate Profiler Report
#'
#' This function reads a dataset from a specified file and generates a profiler report
#' by calling the `profiler_dataframe` function. It validates the input file path and
#' the output markdown file name before proceeding.
#'
#' @param file_path A character string specifying the path to the file containing the data.
#'                  The file must exist. The function currently supports CSV files.
#' @param output_file A character string specifying the name of the output markdown file 
#'                    where the profiler report will be saved. Default is "profiler_report.md".
#' @param sep A character string specifying the separator used in the file. Default is ",".
#'
#' @details The function checks that the `file_path` is a character string and that the 
#'          specified file exists. It reads the data from the file and then passes the 
#'          resulting data frame to the `profiler_dataframe` function to generate the report.
#'
#' @return None. The function does not return a value but modifies the specified markdown file
#'         through the `profiler_dataframe` function.
#'
#' @examples
#' # Example usage with a CSV file
#' profiler_file("data/my_data.csv")
#'
#' @export
profiler_file <- function(file_path, output_file = "profiler_report.md", sep = ",") {
    stopifnot(is.character(file_path), file.exists(file_path))
    stopifnot(is.character(output_file))
    data <- read.csv(file_path, check.names = FALSE, sep = sep)
    profiler_dataframe(data, output_file)
}

#' Generate Profiler Report from Data Frame
#'
#' This function generates a profiler report for a given data frame by calculating 
#' various statistics and writing them to a specified markdown file. It can also 
#' generate visualizations for the variables, interactions, correlations, etc. in the data frame.
#'
#' @param data A data frame for which the profiler report will be generated.
#' @param output_file A character string specifying the name of the output markdown file 
#'                    where the profiler report will be saved. Default is "profiler_report.md".
#'
#' @details The function validates that the input is a data frame and that the output 
#'          file name is a character string. It generates an overview section in the report,
#'          which currently includes dataset statistics, by calling the `write_statistics` 
#'          function. Further functionalities such as variable types and visualizations 
#'          can be added in the future.
#'
#' @return None. The function does not return a value but modifies the specified markdown file.
#'
#' @examples
#' # Example usage with a data frame
#' df <- data.frame(a = 1:5, b = letters[1:5])
#' profiler_dataframe(df)
#'
#' @export
profiler_dataframe <- function(data, output_file = "profiler_report.md") {
    stopifnot(is.data.frame(data))
    stopifnot(is.character(output_file))

    # Overview Section:
    cat("# Overview\n", file = output_file, append = TRUE)
    # 1. Dataset Statistics
    write_statistics(data, output_file)

    # 2. Variable Types
    write_variable_types(data, output_file)

    # Variables Section:
    cat("\n# Variables\n", file = output_file, append = TRUE)
    # draw charts of all columns according to their data types
    # along with some statistics
    write_variables(data, output_file)
}

# print(profiler("data.csv"))
print(profiler(data.frame(a = 1:10, b = 11:20)))
