source("R/handle_numeric.R")
source("R/handle_categorical.R")
source("R/handle_char.R")
source("R/handle_logical.R")

#' Write Variable Statistics to Markdown Report
#' 
#' @description
#' Analyzes variables in a data frame and writes statistical summaries to a markdown file.
#' Currently supports numeric variables, with planned support for character, factor,
#' and logical variables.
#' 
#' @param data A data frame containing the variables to analyze
#' @param output_file Character string specifying the output markdown file path.
#'                    Defaults to "profiler_report.md"
#' 
#' @return NULL invisibly. The function writes results to the specified output file
#'         as a side effect.
#' 
#' @details
#' The function loops through each column in the input data frame and generates
#' appropriate statistical summaries based on the variable type. Currently only
#' numeric variables are supported, with statistics generated by the
#' `.handle_numeric_variables` function.
#' 
#' @examples
#' \dontrun{
#' data <- data.frame(
#'   age = c(25, 30, 35),
#'   income = c(50000, 60000, 75000)
#' )
#' write_variables(data, "my_report.md")
#' }
#' 
#' @export
write_variables <- function(data, output_file = "profiler_report.md") {
    if (!is.data.frame(data)) {
        print("Error: write_variables : data is not a data frame")
        return(NULL)
    }
    if (!is.character(output_file)) {
        print("Error: write_variables : output_file is not a character")
        return(NULL)
    }

    # print("In write_variables")

    # loop through columns and call the function based on the type
    for (col_name in colnames(data)) {
        print(paste("Column name:", col_name))
        column <- data[[col_name]]
        print(paste("Getting variable statistics for", col_name))
        cat("\n### ", col_name, "\n", file = output_file, append = TRUE)

        if (is.numeric(column)) {
            print("Handling numeric variables")
            .handle_numeric_variables(column, output_file)
        } else if (is.character(column)) {
            .handle_character_variables(column, output_file)
        } else if (is.factor(column)) {
            .handle_categorical_variables(column, output_file)
        } else if (is.logical(column)) {
            .handle_logical_variables(column, output_file)
        }
    }
}
